version: "3.9"

services:
  tei:
    build:
      context: .
      dockerfile: Dockerfile.tei
      args:
        MODEL_ID: google/embeddinggemma-300m
    container_name: tei-embeddinggemma
    ports:
      - "8080:80"
    environment:
      HF_TOKEN: "${HUGGING_FACE_HUB_TOKEN}"
    networks:
      - esnet
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8g
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    environment:
      - "ES_JAVA_OPTS=-Xms1512m -Xmx1512m"
      - "ELASTIC_PASSWORD=elastic_password"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - action.auto_create_index=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - esnet
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped

networks:
  esnet:
    driver: bridge

